apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: substreams-tier2-config
data:
  config.yaml: |
    start:
      args:
        - substreams-tier2
      flags:
        verbose: 1
        common-live-blocks-addr: "relayer:13011"
        common-merged-blocks-store-url: "s3://seaweedfs:8333/fireeth-merged-blocks?region=none&insecure=true&access_key_id=any_no_empty_key&secret_access_key=any_no_empty_key"
        common-one-block-store-url: "s3://seaweedfs:8333/fireeth-one-blocks?region=none&insecure=true&access_key_id=any_no_empty_key&secret_access_key=any_no_empty_key"
        common-forked-blocks-store-url: "s3://seaweedfs:8333/fireeth-forked-blocks?region=none&insecure=true&access_key_id=any_no_empty_key&secret_access_key=any_no_empty_key"
        common-system-shutdown-signal-delay: 10s
        substreams-rpc-endpoints: https://eth.rpc.pinax.nework:8545/
        substreams-state-store-url: "s3://seaweedfs:8333/fireeth-state?region=none&insecure=true&access_key_id=any_no_empty_key&secret_access_key=any_no_empty_key"
        substreams-tier2-request-stats: true
        substreams-tier2-grpc-listen-addr: :13045
        