apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: substreams-tier2-config
data:
  config.yaml: |
    start:
      args:
        - substreams-tier2
      flags:
        verbose: 1
        common-metering-plugin: "grpc://sf-metering-v1.service.march.consul.eosn.io:9000?network=goerli"
        common-live-blocks-addr: dns:///goerli-sf-relayer-v4.service.march.consul.eosn.io:9000
        common-merged-blocks-store-url: s3://ceph-gw.service.march.consul.eosn.io:7480/goerli-sf-v4-merged-blocks?region=none&insecure=true
        common-one-block-store-url: s3://ceph-gw.service.march.consul.eosn.io:7480/goerli-sf-v4-one-blocks?region=none&insecure=true
        common-forked-blocks-store-url: s3://ceph-gw.service.march.consul.eosn.io:7480/goerli-sf-v4-forked-blocks?region=none&insecure=true
        common-system-shutdown-signal-delay: 10s
        substreams-rpc-endpoints: http://goerli-erigon.service.march.consul.eosn.io:8545
        substreams-state-store-url: s3://ceph-gw.service.march.consul.eosn.io:7480/goerli-sf-v4-substreams-state?region=none&insecure=true
        substreams-rpc-cache-store-url: s3://ceph-gw.service.march.consul.eosn.io:7480/goerli-sf-v4-rpc-cache?region=none&insecure=true
        substreams-tier2-grpc-listen-addr: :9000


        # verbose: 1
        # common-live-blocks-addr: "relayer:13011"
        # common-merged-blocks-store-url: "s3://seaweedfs:8333/fireeth-merged-blocks?region=none&insecure=true&access_key_id=any_no_empty_key&secret_access_key=any_no_empty_key"
        # common-one-block-store-url: "s3://seaweedfs:8333/fireeth-one-blocks?region=none&insecure=true&access_key_id=any_no_empty_key&secret_access_key=any_no_empty_key"
        # common-forked-blocks-store-url: "s3://seaweedfs:8333/fireeth-forked-blocks?region=none&insecure=true&access_key_id=any_no_empty_key&secret_access_key=any_no_empty_key"
        # common-system-shutdown-signal-delay: 10s
        # substreams-rpc-endpoints: https://eth.rpc.pinax.nework:8545/
        # substreams-state-store-url: "s3://seaweedfs:8333/fireeth-state?region=none&insecure=true&access_key_id=any_no_empty_key&secret_access_key=any_no_empty_key"
        # substreams-tier2-grpc-listen-addr: :13045
        # metrics-listen-addr: ":9102"
        