---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sf-ethereum
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - scaledObject.yaml
  # - autoscaler.yaml
