apiVersion: v1
kind: Service
metadata:
  name: substreams-tier2
  labels:
    app: substreams-tier2
spec:
  type: ClusterIP
  selector:
    app: substreams-tier2
  ports:
    - name: grpc
      port: 9000
      protocol: TCP
      targetPort: grpc
    - name: prom
      port: 9102
      protocol: TCP
      targetPort: prom
