apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - weave.yaml                    # Flux dashboard
  # - traefik.yaml                  # Ingress controller
  # - loki.yaml                     # Logs
  # - tempo.yaml                    # Traces
  # - odigos.yaml                   # Instrumentation
  # - otel.yaml                     # OpenTelemetry
  # - fluent.yaml                   # K8s logs transmission
  - prometheus.yaml               # Metrics
  - metallb.yaml                  # Load balancer
  # - openebs.yaml                  # Dynamic storage
  # - keda.yaml                     # Horizontal autoscaling
