apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: firehose-config
data:
  config.yaml: |
    start:
      args:
      - firehose
      flags:
        verbose: "1"
        common-chain-id: "1"
        common-network-id: "1"
        log-to-file: false
        data-dir: "/var/lib/fireeth"
        common-one-block-store-url: "s3://seaweedfs:8333/fireeth-one-blocks?region=none&insecure=true&access_key_id=any_no_empty_key&secret_access_key=any_no_empty_key"
        common-merged-blocks-store-url: "s3://seaweedfs:8333/fireeth-merged-blocks?region=none&insecure=true&access_key_id=any_no_empty_key&secret_access_key=any_no_empty_key"
        common-forked-blocks-store-url: "s3://seaweedfs:8333/fireeth-forked-blocks?region=none&insecure=true&access_key_id=any_no_empty_key&secret_access_key=any_no_empty_key"
        common-index-store-url: "s3://seaweedfs:8333/fireeth-index?region=none&insecure=true&access_key_id=any_no_empty_key&secret_access_key=any_no_empty_key"
        common-live-blocks-addr: "relayer:13011"
        # common-block-index-sizes: "10000"
        # firehose-grpc-listen-addr: ":13042"
        # firehose-rate-limit-bucket-size: "20"
        # firehose-rate-limit-bucket-fill-rate: "1s"
