apiVersion: apps/v1
kind: Deployment
metadata:
  name: substreams-tier1
spec:
  selector:
    matchLabels:
      app: substreams-tier1
  replicas: 1
  template:
    metadata:
      labels:
        app: substreams-tier1
    spec:
      containers:
        - name: substreams-tier1
          image: fireeth
          args:
            - "start"
            - "-c"
            - "/config/config.yaml"
          ports:
            - name: grpc
              # containerPort: 13044
              containerPort: 9000
              protocol: TCP
            - name: prom
              containerPort: 9102
              protocol: TCP
          env:
            - name: SF_TRACING
              value: "otelcol://172.22.127.10:80/otc"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: DSTORE_S3_BUFFERED_READ
              value: "true"
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: substreams-tier1-config