apiVersion: v1
kind: Service
metadata:
  name: substreams-tier1
spec:
  type: NodePort
  selector:
    app: substreams-tier1
  ports:
    - name: grpc
      # port: 13044
      port: 9000
      protocol: TCP
      targetPort: grpc
      nodePort: 30044
    - name: prom
      port: 9102
      protocol: TCP
      targetPort: prom
